WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 512
VIRTUAL_HEIGHT = 288

BACKGROUND_SCROLL_SPEED = 15
BACKGROUND_LOOPING_POINT = 512

SCROLL_SPEED = 50
TERRAIN_SCROLL_SPEED = SCROLL_SPEED

TILE_SIZE = 4 

TERRAIN_TILE_HEIGHT = 12
TERRAIN_TILE_WIDTH = 12

SHIP_SPEED = 120
SHIP_PROJECTILE_SPEED = 240

SCREEN_PADDING_TOP = 8
SCREEN_PADDING_LEFT = 8
SCREEN_PADDING_RIGHT = 8


